import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="container max-w-4xl py-12">
      <div className="mb-8">
        <Link
          href="/"
          className="text-muted-foreground hover:text-foreground text-sm"
        >
          ← Back to Home
        </Link>
      </div>

      <h1 className="mb-8 text-4xl font-bold">Terms of Service</h1>

      <div className="prose prose-invert max-w-none space-y-6">
        <p className="text-muted-foreground">Last updated: February 18, 2026</p>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">1. Acceptance of Terms</h2>
          <p>
            By accessing and using BriefTube (&quot;the Service&quot;), you
            accept and agree to be bound by the terms and provisions of this
            agreement. If you do not agree to these terms, please do not use the
            Service.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">2. Description of Service</h2>
          <p>
            BriefTube is a service that monitors YouTube channels, generates
            AI-powered summaries, converts them to audio, and delivers them to
            your Telegram account.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">3. User Accounts</h2>
          <ul className="text-muted-foreground ml-6 list-disc space-y-2">
            <li>You must use a valid Google account to access the Service</li>
            <li>
              You are responsible for maintaining the security of your account
            </li>
            <li>You must be at least 13 years old to use the Service</li>
            <li>
              One account per person - multiple accounts are not permitted
            </li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">4. Subscription Plans</h2>
          <p>BriefTube offers free and paid subscription plans:</p>
          <ul className="text-muted-foreground ml-6 list-disc space-y-2">
            <li>
              <strong>Free Plan:</strong> Limited to 5 YouTube channels
            </li>
            <li>
              <strong>Pro Plan:</strong> Unlimited channels, priority
              processing, and additional features
            </li>
            <li>Subscriptions are billed monthly via Stripe</li>
            <li>You can upgrade, downgrade, or cancel at any time</li>
            <li>Refunds are handled on a case-by-case basis</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">5. Acceptable Use</h2>
          <p>You agree NOT to:</p>
          <ul className="text-muted-foreground ml-6 list-disc space-y-2">
            <li>Use the Service for any illegal purposes</li>
            <li>Attempt to circumvent usage limits or restrictions</li>
            <li>Abuse, harass, or spam the Service</li>
            <li>Reverse engineer or copy the Service</li>
            <li>Use automated tools to abuse the Service</li>
            <li>Share your account with others</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">
            6. Content and Intellectual Property
          </h2>
          <ul className="text-muted-foreground ml-6 list-disc space-y-2">
            <li>
              Generated summaries are created from publicly available YouTube
              content
            </li>
            <li>Audio summaries are for your personal use only</li>
            <li>
              Do not redistribute or resell summaries generated by the Service
            </li>
            <li>BriefTube respects copyright and DMCA</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">7. Service Availability</h2>
          <p>
            We strive to provide reliable service, but we do not guarantee 100%
            uptime. The Service may be temporarily unavailable due to
            maintenance, updates, or technical issues.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">8. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your account if you
            violate these terms. You may also delete your account at any time
            from the settings page.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">
            9. Disclaimer of Warranties
          </h2>
          <p>
            The Service is provided &quot;as is&quot; without warranties of any
            kind, either express or implied. We do not guarantee the accuracy of
            AI-generated summaries.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">
            10. Limitation of Liability
          </h2>
          <p>
            BriefTube shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages resulting from your use of the
            Service.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">11. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. We will
            notify users of significant changes via email or through the
            Service.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">12. Contact</h2>
          <p>For questions about these Terms of Service, contact us at:</p>
          <p className="text-muted-foreground">Email: support@brieftube.com</p>
        </section>
      </div>
    </div>
  );
}
